version: "3.9"

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:1.0.20210914-ls109
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SERVERURL=${WIREGUARD_SERVER_URL}
      - SERVERPORT=${WIREGUARD_PORT}
      - PEERS=${WIREGUARD_PEERS}
      - PEERDNS=${WIREGUARD_PEER_DNS}
      - INTERNAL_SUBNET=${WIREGUARD_SUBNET}
    ports:
      - "${WIREGUARD_PORT}:51820/udp"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - wireguard_config:/config
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  wireguard_config:
